
import { ChemicalElement, ElementCategory } from './types';

export const CATEGORY_COLORS: Record<ElementCategory, string> = {
  'alkali-metal': '#ff6b6b', // Red-ish
  'alkaline-earth-metal': '#fcc419', // Yellow-ish
  'transition-metal': '#5c7cfa', // Blue
  'post-transition-metal': '#20c997', // Teal
  'metalloid': '#94d82d', // Lime
  'non-metal': '#ff922b', // Orange
  'halogen': '#845ef7', // Purple
  'noble-gas': '#f06595', // Pink
  'lanthanide': '#cc5de8', // Grape
  'actinide': '#e599f7', // Light Purple
  'unknown': '#495057', // Gray
};

export const ELEMENTS: ChemicalElement[] = [
  // Period 1
  { number: 1, symbol: 'H', name: 'Hydrogen', atomic_mass: "1.0", category: 'non-metal', group: 1, period: 1, gridX: 1, gridY: 1, electron_configuration: "1s1", density: 0.08988, melt: 14.01, boil: 20.28, discovered_by: "Henry Cavendish", year_discovered: 1766, summary: "Hydrogen is the lightest and most abundant element in the universe, constituting roughly 75% of all baryonic mass. Stars shine primarily due to the fusion of hydrogen into helium." },
  { number: 2, symbol: 'He', name: 'Helium', atomic_mass: "4.0", category: 'noble-gas', group: 18, period: 1, gridX: 18, gridY: 1, electron_configuration: "1s2", density: 0.1786, melt: 0.95, boil: 4.22, discovered_by: "Pierre Janssen", year_discovered: 1868, summary: "Helium is the second lightest and second most abundant element. It was discovered in the solar spectrum before being found on Earth. It remains liquid down to absolute zero at standard pressure." },

  // Period 2
  { number: 3, symbol: 'Li', name: 'Lithium', atomic_mass: "7.0", category: 'alkali-metal', group: 1, period: 2, gridX: 1, gridY: 2, electron_configuration: "[He] 2s1", density: 0.534, melt: 453.69, boil: 1615, discovered_by: "Johan August Arfwedson", year_discovered: 1817, summary: "Lithium is the lightest metal and the lightest solid element. It is highly reactive and flammable, and is stored in mineral oil. It is a key component in modern rechargeable batteries." },
  { number: 4, symbol: 'Be', name: 'Beryllium', atomic_mass: "9.0", category: 'alkaline-earth-metal', group: 2, period: 2, gridX: 2, gridY: 2, electron_configuration: "[He] 2s2", density: 1.85, melt: 1560, boil: 2742, discovered_by: "Louis Nicolas Vauquelin", year_discovered: 1798, summary: "Beryllium is a steel-grey, strong, lightweight and brittle alkaline earth metal. It is relatively rare in the universe and is used to make X-ray windows and strong, non-sparking tools." },
  { number: 5, symbol: 'B', name: 'Boron', atomic_mass: "10.8", category: 'metalloid', group: 13, period: 2, gridX: 13, gridY: 2, electron_configuration: "[He] 2s2 2p1", density: 2.08, melt: 2349, boil: 4200, discovered_by: "Joseph Louis Gay-Lussac", year_discovered: 1808, summary: "Boron is a hard, brittle, lustrous black metalloid. It is an essential nutrient for plants and is used in heat-resistant glass (Pyrex) and detergents." },
  { number: 6, symbol: 'C', name: 'Carbon', atomic_mass: "12.0", category: 'non-metal', group: 14, period: 2, gridX: 14, gridY: 2, electron_configuration: "[He] 2s2 2p2", density: 2.267, melt: 3800, boil: 4300, discovered_by: "Egyptians", year_discovered: "Ancient", summary: "Carbon is the basis of all known life. It possesses the unique ability to form vast chains and rings of atoms, leading to millions of organic compounds. It exists as graphite, diamond, and buckyballs." },
  { number: 7, symbol: 'N', name: 'Nitrogen', atomic_mass: "14.0", category: 'non-metal', group: 15, period: 2, gridX: 15, gridY: 2, electron_configuration: "[He] 2s2 2p3", density: 1.2506, melt: 63.15, boil: 77.36, discovered_by: "Daniel Rutherford", year_discovered: 1772, summary: "Nitrogen makes up 78% of Earth's atmosphere. It is a crucial component of amino acids and nucleic acids, making it vital for all living organisms." },
  { number: 8, symbol: 'O', name: 'Oxygen', atomic_mass: "16.0", category: 'non-metal', group: 16, period: 2, gridX: 16, gridY: 2, electron_configuration: "[He] 2s2 2p4", density: 1.429, melt: 54.36, boil: 90.20, discovered_by: "Carl Wilhelm Scheele", year_discovered: 1774, summary: "Oxygen is the third most abundant element in the universe and the most abundant in the Earth's crust. It is highly reactive and essential for respiration and combustion." },
  { number: 9, symbol: 'F', name: 'Fluorine', atomic_mass: "19.0", category: 'halogen', group: 17, period: 2, gridX: 17, gridY: 2, electron_configuration: "[He] 2s2 2p5", density: 1.696, melt: 53.53, boil: 85.03, discovered_by: "Henri Moissan", year_discovered: 1886, summary: "Fluorine is the most electronegative and reactive of all elements. It can etch glass and even react with noble gases. It is commonly used in toothpaste and Teflon." },
  { number: 10, symbol: 'Ne', name: 'Neon', atomic_mass: "20.2", category: 'noble-gas', group: 18, period: 2, gridX: 18, gridY: 2, electron_configuration: "[He] 2s2 2p6", density: 0.9002, melt: 24.56, boil: 27.07, discovered_by: "Morris Travers", year_discovered: 1898, summary: "Neon is a colorless, odorless noble gas that glows a distinct reddish-orange when used in high-voltage discharge tubes, known as 'neon lights'." },

  // Period 3
  { number: 11, symbol: 'Na', name: 'Sodium', atomic_mass: "23.0", category: 'alkali-metal', group: 1, period: 3, gridX: 1, gridY: 3, electron_configuration: "[Ne] 3s1", density: 0.968, melt: 370.87, boil: 1156, discovered_by: "Humphry Davy", year_discovered: 1807, summary: "Sodium is a soft, silvery-white metal that explodes on contact with water. It is essential for nerve function in animals and is a primary component of table salt." },
  { number: 12, symbol: 'Mg', name: 'Magnesium', atomic_mass: "24.3", category: 'alkaline-earth-metal', group: 2, period: 3, gridX: 2, gridY: 3, electron_configuration: "[Ne] 3s2", density: 1.738, melt: 923, boil: 1363, discovered_by: "Joseph Black", year_discovered: 1755, summary: "Magnesium is a light, strong metal used in aerospace and automotive applications. It burns with a brilliant white light and is central to the chlorophyll molecule in plants." },
  { number: 13, symbol: 'Al', name: 'Aluminium', atomic_mass: "27.0", category: 'post-transition-metal', group: 13, period: 3, gridX: 13, gridY: 3, electron_configuration: "[Ne] 3s2 3p1", density: 2.70, melt: 933.47, boil: 2792, discovered_by: "Hans Christian Ørsted", year_discovered: 1825, summary: "Aluminium is the most abundant metal in Earth's crust. It is lightweight, non-toxic, and resistant to corrosion, making it ubiquitous in modern manufacturing." },
  { number: 14, symbol: 'Si', name: 'Silicon', atomic_mass: "28.1", category: 'metalloid', group: 14, period: 3, gridX: 14, gridY: 3, electron_configuration: "[Ne] 3s2 3p2", density: 2.329, melt: 1687, boil: 3538, discovered_by: "Jöns Jacob Berzelius", year_discovered: 1824, summary: "Silicon is the basis of the modern digital age, serving as the primary semiconductor in computer chips. It is the second most abundant element in the Earth's crust." },
  { number: 15, symbol: 'P', name: 'Phosphorus', atomic_mass: "31.0", category: 'non-metal', group: 15, period: 3, gridX: 15, gridY: 3, electron_configuration: "[Ne] 3s2 3p3", density: 1.823, melt: 317.30, boil: 550, discovered_by: "Hennig Brand", year_discovered: 1669, summary: "Phosphorus exists in several forms, most notably white (explosive) and red (matches). It is a vital component of DNA, RNA, and ATP, the energy currency of cells." },
  { number: 16, symbol: 'S', name: 'Sulfur', atomic_mass: "32.1", category: 'non-metal', group: 16, period: 3, gridX: 16, gridY: 3, electron_configuration: "[Ne] 3s2 3p4", density: 2.07, melt: 388.36, boil: 717.8, discovered_by: "Ancient", year_discovered: "Ancient", summary: "Sulfur is a bright yellow solid known since antiquity as 'brimstone'. It is found near volcanoes and is essential for fertilizers and chemical processes like vulcanization." },
  { number: 17, symbol: 'Cl', name: 'Chlorine', atomic_mass: "35.5", category: 'halogen', group: 17, period: 3, gridX: 17, gridY: 3, electron_configuration: "[Ne] 3s2 3p5", density: 3.2, melt: 171.6, boil: 239.11, discovered_by: "Carl Wilhelm Scheele", year_discovered: 1774, summary: "Chlorine is a yellow-green toxic gas used as a disinfectant and bleach. It was the first poison gas used in warfare but is also essential in the form of chloride ions for life." },
  { number: 18, symbol: 'Ar', name: 'Argon', atomic_mass: "40.0", category: 'noble-gas', group: 18, period: 3, gridX: 18, gridY: 3, electron_configuration: "[Ne] 3s2 3p6", density: 1.784, melt: 83.80, boil: 87.30, discovered_by: "Lord Rayleigh", year_discovered: 1894, summary: "Argon is the third most abundant gas in Earth's atmosphere (approx 1%). It is completely inert and used in welding shields, incandescent light bulbs, and lasers." },

  // Period 4
  { number: 19, symbol: 'K', name: 'Potassium', atomic_mass: "39.1", category: 'alkali-metal', group: 1, period: 4, gridX: 1, gridY: 4, electron_configuration: "[Ar] 4s1", density: 0.862, melt: 336.7, boil: 1032, discovered_by: "Humphry Davy", year_discovered: 1807, summary: "Potassium is a soft, silvery metal that reacts violently with water. It is a vital electrolyte in the human body, regulating heart rhythm and nerve transmission." },
  { number: 20, symbol: 'Ca', name: 'Calcium', atomic_mass: "40.1", category: 'alkaline-earth-metal', group: 2, period: 4, gridX: 2, gridY: 4, electron_configuration: "[Ar] 4s2", density: 1.55, melt: 1115, boil: 1757, discovered_by: "Humphry Davy", year_discovered: 1808, summary: "Calcium is essential for living organisms, particularly in cell physiology and the mineralization of bones and shells. It is the fifth most abundant element in the Earth's crust." },
  { number: 21, symbol: 'Sc', name: 'Scandium', atomic_mass: "45.0", category: 'transition-metal', group: 3, period: 4, gridX: 3, gridY: 4, electron_configuration: "[Ar] 3d1 4s2", density: 2.985, melt: 1814, boil: 3109, discovered_by: "Lars Fredrik Nilson", year_discovered: 1879, summary: "Scandium is a silvery-white metallic element that historically had few uses but is now used in aluminium alloys for aerospace components and sports equipment." },
  { number: 22, symbol: 'Ti', name: 'Titanium', atomic_mass: "47.9", category: 'transition-metal', group: 4, period: 4, gridX: 4, gridY: 4, electron_configuration: "[Ar] 3d2 4s2", density: 4.506, melt: 1941, boil: 3560, discovered_by: "William Gregor", year_discovered: 1791, summary: "Titanium is renowned for its high strength-to-weight ratio and corrosion resistance. It is used in aerospace, medical implants, and jewelry." },
  { number: 23, symbol: 'V', name: 'Vanadium', atomic_mass: "50.9", category: 'transition-metal', group: 5, period: 4, gridX: 5, gridY: 4, electron_configuration: "[Ar] 3d3 4s2", density: 6.0, melt: 2183, boil: 3680, discovered_by: "Andrés Manuel del Río", year_discovered: 1801, summary: "Vanadium is a hard, grey, ductile transition metal. It is primarily used as a steel additive to produce high-strength alloys for tools and axles." },
  { number: 24, symbol: 'Cr', name: 'Chromium', atomic_mass: "52.0", category: 'transition-metal', group: 6, period: 4, gridX: 6, gridY: 4, electron_configuration: "[Ar] 3d5 4s1", density: 7.19, melt: 2180, boil: 2944, discovered_by: "Louis Nicolas Vauquelin", year_discovered: 1797, summary: "Chromium is a lustrous, hard metal known for its high polish and corrosion resistance. It is the main additive in stainless steel and used in chrome plating." },
  { number: 25, symbol: 'Mn', name: 'Manganese', atomic_mass: "55.0", category: 'transition-metal', group: 7, period: 4, gridX: 7, gridY: 4, electron_configuration: "[Ar] 3d5 4s2", density: 7.21, melt: 1519, boil: 2334, discovered_by: "Johan Gadolin", year_discovered: 1774, summary: "Manganese is a metal with important industrial metal alloy uses, particularly in stainless steels. It is also an essential trace nutrient for all known forms of life." },
  { number: 26, symbol: 'Fe', name: 'Iron', atomic_mass: "55.8", category: 'transition-metal', group: 8, period: 4, gridX: 8, gridY: 4, electron_configuration: "[Ar] 3d6 4s2", density: 7.874, melt: 1811, boil: 3134, discovered_by: "Ancient", year_discovered: "Ancient", summary: "Iron is the most common element in the Earth's mass. It is the backbone of modern civilization as the primary constituent of steel and is vital for oxygen transport in blood." },
  { number: 27, symbol: 'Co', name: 'Cobalt', atomic_mass: "59.0", category: 'transition-metal', group: 9, period: 4, gridX: 9, gridY: 4, electron_configuration: "[Ar] 3d7 4s2", density: 8.90, melt: 1768, boil: 3200, discovered_by: "Georg Brandt", year_discovered: 1735, summary: "Cobalt is a hard, lustrous, silver-grey metal. It is used in superalloys for jet engines, in rechargeable batteries, and its salts produce intense blue pigments." },
  { number: 28, symbol: 'Ni', name: 'Nickel', atomic_mass: "58.7", category: 'transition-metal', group: 10, period: 4, gridX: 10, gridY: 4, electron_configuration: "[Ar] 3d8 4s2", density: 8.908, melt: 1728, boil: 3186, discovered_by: "Axel Fredrik Cronstedt", year_discovered: 1751, summary: "Nickel is a silvery-white metal with a slight golden tinge. It resists corrosion and is used in plating, stainless steel, coins, and magnets." },
  { number: 29, symbol: 'Cu', name: 'Copper', atomic_mass: "63.5", category: 'transition-metal', group: 11, period: 4, gridX: 11, gridY: 4, electron_configuration: "[Ar] 3d10 4s1", density: 8.96, melt: 1357.77, boil: 2835, discovered_by: "Ancient", year_discovered: "Ancient", summary: "Copper is a reddish-orange, soft metal with very high thermal and electrical conductivity. It was one of the first metals used by humans and is essential for electronics." },
  { number: 30, symbol: 'Zn', name: 'Zinc', atomic_mass: "65.4", category: 'transition-metal', group: 12, period: 4, gridX: 12, gridY: 4, electron_configuration: "[Ar] 3d10 4s2", density: 7.14, melt: 692.68, boil: 1180, discovered_by: "Andreas Sigismund Marggraf", year_discovered: 1746, summary: "Zinc is a bluish-white metal primarily used to galvanize steel against corrosion. It is also an essential mineral for human health." },
  { number: 31, symbol: 'Ga', name: 'Gallium', atomic_mass: "69.7", category: 'post-transition-metal', group: 13, period: 4, gridX: 13, gridY: 4, electron_configuration: "[Ar] 3d10 4s2 4p1", density: 5.91, melt: 302.91, boil: 2673, discovered_by: "Lecoq de Boisbaudran", year_discovered: 1875, summary: "Gallium is a soft metal that melts in the palm of your hand. It is used in semiconductors, LEDs (blue and violet), and solar panels." },
  { number: 32, symbol: 'Ge', name: 'Germanium', atomic_mass: "72.6", category: 'metalloid', group: 14, period: 4, gridX: 14, gridY: 4, electron_configuration: "[Ar] 3d10 4s2 4p2", density: 5.323, melt: 1211.40, boil: 3106, discovered_by: "Clemens Winkler", year_discovered: 1886, summary: "Germanium is a lustrous, hard-brittle metalloid. It was the material used in the first transistors before being largely replaced by silicon." },
  { number: 33, symbol: 'As', name: 'Arsenic', atomic_mass: "74.9", category: 'metalloid', group: 15, period: 4, gridX: 15, gridY: 4, electron_configuration: "[Ar] 3d10 4s2 4p3", density: 5.727, melt: 1090, boil: 887, discovered_by: "Albertus Magnus", year_discovered: 1250, summary: "Arsenic is notorious as a poison, but it also has uses in semiconductors and wood preservation. It has metallic and non-metallic allotropes." },
  { number: 34, symbol: 'Se', name: 'Selenium', atomic_mass: "79.0", category: 'non-metal', group: 16, period: 4, gridX: 16, gridY: 4, electron_configuration: "[Ar] 3d10 4s2 4p4", density: 4.81, melt: 494, boil: 958, discovered_by: "Jöns Jacob Berzelius", year_discovered: 1817, summary: "Selenium is a non-metal with photoconductive properties, making it useful in photocopiers and solar cells. It is also a trace nutrient." },
  { number: 35, symbol: 'Br', name: 'Bromine', atomic_mass: "79.9", category: 'halogen', group: 17, period: 4, gridX: 17, gridY: 4, electron_configuration: "[Ar] 3d10 4s2 4p5", density: 3.1028, melt: 265.8, boil: 332.0, discovered_by: "Antoine Jérôme Balard", year_discovered: 1826, summary: "Bromine is the only non-metallic element that is liquid at room temperature. It is a fuming red-brown liquid, corrosive and toxic, used in flame retardants." },
  { number: 36, symbol: 'Kr', name: 'Krypton', atomic_mass: "83.8", category: 'noble-gas', group: 18, period: 4, gridX: 18, gridY: 4, electron_configuration: "[Ar] 3d10 4s2 4p6", density: 3.749, melt: 115.79, boil: 119.93, discovered_by: "William Ramsay", year_discovered: 1898, summary: "Krypton is a colorless, odorless noble gas used in high-speed photography flash lamps and fluorescent light bulbs. It was once used to define the length of the meter." },

  // Period 5
  { number: 37, symbol: 'Rb', name: 'Rubidium', atomic_mass: "85.5", category: 'alkali-metal', group: 1, period: 5, gridX: 1, gridY: 5, electron_configuration: "[Kr] 5s1", density: 1.532, melt: 312.46, boil: 961, discovered_by: "Robert Bunsen", year_discovered: 1861, summary: "Rubidium is a soft, silvery-white metal that ignites spontaneously in air. It is used in atomic clocks and vacuum tubes." },
  { number: 38, symbol: 'Sr', name: 'Strontium', atomic_mass: "87.6", category: 'alkaline-earth-metal', group: 2, period: 5, gridX: 2, gridY: 5, electron_configuration: "[Kr] 5s2", density: 2.64, melt: 1050, boil: 1655, discovered_by: "William Cruickshank", year_discovered: 1787, summary: "Strontium is a soft silver-white metal. Its salts burn with a brilliant red flame, making them a key ingredient in fireworks and flares." },
  { number: 39, symbol: 'Y', name: 'Yttrium', atomic_mass: "88.9", category: 'transition-metal', group: 3, period: 5, gridX: 3, gridY: 5, electron_configuration: "[Kr] 4d1 5s2", density: 4.472, melt: 1799, boil: 3609, discovered_by: "Johan Gadolin", year_discovered: 1794, summary: "Yttrium is a silvery-metallic transition metal. It is used in LEDs, phosphors, and superconductors, and was the first rare-earth element discovered." },
  { number: 40, symbol: 'Zr', name: 'Zirconium', atomic_mass: "91.2", category: 'transition-metal', group: 4, period: 5, gridX: 4, gridY: 5, electron_configuration: "[Kr] 4d2 5s2", density: 6.52, melt: 2128, boil: 4682, discovered_by: "Martin Heinrich Klaproth", year_discovered: 1789, summary: "Zirconium is a lustrous, grey-white metal that strongly resists corrosion. It is widely used in nuclear reactors due to its low neutron absorption." },
  { number: 41, symbol: 'Nb', name: 'Niobium', atomic_mass: "92.9", category: 'transition-metal', group: 5, period: 5, gridX: 5, gridY: 5, electron_configuration: "[Kr] 4d4 5s1", density: 8.57, melt: 2750, boil: 5017, discovered_by: "Charles Hatchett", year_discovered: 1801, summary: "Niobium is a ductile grey metal used in high-strength, low-alloy steels and superconducting magnets for MRI scanners." },
  { number: 42, symbol: 'Mo', name: 'Molybdenum', atomic_mass: "95.9", category: 'transition-metal', group: 6, period: 5, gridX: 6, gridY: 5, electron_configuration: "[Kr] 4d5 5s1", density: 10.28, melt: 2896, boil: 4912, discovered_by: "Carl Wilhelm Scheele", year_discovered: 1778, summary: "Molybdenum has one of the highest melting points of all pure elements. It is used in high-temperature steel alloys and lubricants." },
  { number: 43, symbol: 'Tc', name: 'Technetium', atomic_mass: "[99]", category: 'transition-metal', group: 7, period: 5, gridX: 7, gridY: 5, electron_configuration: "[Kr] 4d5 5s2", density: 11, melt: 2430, boil: 4538, discovered_by: "Emilio Segrè", year_discovered: 1937, summary: "Technetium was the first artificially produced element. It is radioactive and widely used in nuclear medicine for diagnostic imaging." },
  { number: 44, symbol: 'Ru', name: 'Ruthenium', atomic_mass: "101.1", category: 'transition-metal', group: 8, period: 5, gridX: 8, gridY: 5, electron_configuration: "[Kr] 4d7 5s1", density: 12.45, melt: 2607, boil: 4423, discovered_by: "Karl Ernst Claus", year_discovered: 1844, summary: "Ruthenium is a rare, hard, white metal of the platinum group. It is used in wear-resistant electrical contacts and thick-film resistors." },
  { number: 45, symbol: 'Rh', name: 'Rhodium', atomic_mass: "102.9", category: 'transition-metal', group: 9, period: 5, gridX: 9, gridY: 5, electron_configuration: "[Kr] 4d8 5s1", density: 12.41, melt: 2237, boil: 3968, discovered_by: "William Hyde Wollaston", year_discovered: 1803, summary: "Rhodium is one of the rarest and most expensive precious metals. It is highly reflective and resistant to corrosion, used in catalytic converters and jewelry plating." },
  { number: 46, symbol: 'Pd', name: 'Palladium', atomic_mass: "106.4", category: 'transition-metal', group: 10, period: 5, gridX: 10, gridY: 5, electron_configuration: "[Kr] 4d10", density: 12.023, melt: 1828.05, boil: 3236, discovered_by: "William Hyde Wollaston", year_discovered: 1803, summary: "Palladium is a lustrous silvery-white metal that can absorb 900 times its volume in hydrogen gas. It is crucial for catalytic converters and fuel cells." },
  { number: 47, symbol: 'Ag', name: 'Silver', atomic_mass: "107.9", category: 'transition-metal', group: 11, period: 5, gridX: 11, gridY: 5, electron_configuration: "[Kr] 4d10 5s1", density: 10.49, melt: 1234.93, boil: 2435, discovered_by: "Ancient", year_discovered: "Ancient", summary: "Silver has the highest electrical and thermal conductivity of any metal. It is valued for jewelry, coins, electronics, and photography." },
  { number: 48, symbol: 'Cd', name: 'Cadmium', atomic_mass: "112.4", category: 'transition-metal', group: 12, period: 5, gridX: 12, gridY: 5, electron_configuration: "[Kr] 4d10 5s2", density: 8.65, melt: 594.22, boil: 1040, discovered_by: "Friedrich Stromeyer", year_discovered: 1817, summary: "Cadmium is a toxic, soft bluish-white metal. It is used in rechargeable batteries (NiCd) and as a pigment, though its use is decreasing due to toxicity." },
  { number: 49, symbol: 'In', name: 'Indium', atomic_mass: "114.8", category: 'post-transition-metal', group: 13, period: 5, gridX: 13, gridY: 5, electron_configuration: "[Kr] 4d10 5s2 5p1", density: 7.31, melt: 429.75, boil: 2345, discovered_by: "Ferdinand Reich", year_discovered: 1863, summary: "Indium is a very soft metal that creates a high-pitched 'cry' when bent. It is transparent and conductive as indium tin oxide, used in touch screens." },
  { number: 50, symbol: 'Sn', name: 'Tin', atomic_mass: "118.7", category: 'post-transition-metal', group: 14, period: 5, gridX: 14, gridY: 5, electron_configuration: "[Kr] 4d10 5s2 5p2", density: 7.31, melt: 505.08, boil: 2875, discovered_by: "Ancient", year_discovered: "Ancient", summary: "Tin is a silvery metal that does not oxidize easily in air. It has been used since the Bronze Age to harden copper and is used today in solder and plating." },
  { number: 51, symbol: 'Sb', name: 'Antimony', atomic_mass: "121.8", category: 'metalloid', group: 15, period: 5, gridX: 15, gridY: 5, electron_configuration: "[Kr] 4d10 5s2 5p3", density: 6.697, melt: 903.78, boil: 1860, discovered_by: "Ancient", year_discovered: "Ancient", summary: "Antimony is a lustrous gray metalloid used in lead-acid batteries, flame retardants, and semiconductors. Its compounds have been used in cosmetics since ancient times." },
  { number: 52, symbol: 'Te', name: 'Tellurium', atomic_mass: "127.6", category: 'metalloid', group: 16, period: 5, gridX: 16, gridY: 5, electron_configuration: "[Kr] 4d10 5s2 5p4", density: 6.24, melt: 722.66, boil: 1261, discovered_by: "Franz-Joseph Müller von Reichenstein", year_discovered: 1782, summary: "Tellurium is a brittle, rare silver-white metalloid. It is used in cadmium telluride solar panels and to improve the machinability of copper and steel." },
  { number: 53, symbol: 'I', name: 'Iodine', atomic_mass: "126.9", category: 'halogen', group: 17, period: 5, gridX: 17, gridY: 5, electron_configuration: "[Kr] 4d10 5s2 5p5", density: 4.933, melt: 386.85, boil: 457.4, discovered_by: "Bernard Courtois", year_discovered: 1811, summary: "Iodine is a lustrous violet-black solid that sublimes into a purple vapor. It is an essential nutrient for thyroid health and is used as an antiseptic." },
  { number: 54, symbol: 'Xe', name: 'Xenon', atomic_mass: "131.3", category: 'noble-gas', group: 18, period: 5, gridX: 18, gridY: 5, electron_configuration: "[Kr] 4d10 5s2 5p6", density: 5.894, melt: 161.4, boil: 165.03, discovered_by: "William Ramsay", year_discovered: 1898, summary: "Xenon is a heavy, dense noble gas. It produces a bright blue glow in discharge tubes and is used in ion thrusters for spacecraft propulsion." },

  // Period 6
  { number: 55, symbol: 'Cs', name: 'Cesium', atomic_mass: "132.9", category: 'alkali-metal', group: 1, period: 6, gridX: 1, gridY: 6, electron_configuration: "[Xe] 6s1", density: 1.93, melt: 301.59, boil: 944, discovered_by: "Robert Bunsen", year_discovered: 1860, summary: "Cesium is the most reactive of all metals and is liquid at near room temperature. It is defined as the standard for the second in atomic clocks." },
  { number: 56, symbol: 'Ba', name: 'Barium', atomic_mass: "137.3", category: 'alkaline-earth-metal', group: 2, period: 6, gridX: 2, gridY: 6, electron_configuration: "[Xe] 6s2", density: 3.51, melt: 1000, boil: 2170, discovered_by: "Carl Wilhelm Scheele", year_discovered: 1772, summary: "Barium is a soft, silvery metal that oxidizes rapidly. Its compounds are used in drilling fluids, green fireworks, and medical imaging (barium swallows)." },
  
  // Lanthanides (grid row 9)
  { number: 57, symbol: 'La', name: 'Lanthanum', atomic_mass: "138.9", category: 'lanthanide', group: 3, period: 6, gridX: 4, gridY: 9, electron_configuration: "[Xe] 5d1 6s2", density: 6.162, melt: 1193, boil: 3737, discovered_by: "Carl Gustaf Mosander", year_discovered: 1839, summary: "Lanthanum is a soft, ductile silvery-white metal. It is used in high-refractive-index glass, hybrid car batteries, and flint." },
  { number: 58, symbol: 'Ce', name: 'Cerium', atomic_mass: "140.1", category: 'lanthanide', group: 3, period: 6, gridX: 5, gridY: 9, electron_configuration: "[Xe] 4f1 5d1 6s2", density: 6.77, melt: 1068, boil: 3716, discovered_by: "Martin Heinrich Klaproth", year_discovered: 1803, summary: "Cerium is the most abundant rare-earth element. It is the primary component of mischmetal used in lighter flints and is also used in catalytic converters." },
  { number: 59, symbol: 'Pr', name: 'Praseodymium', atomic_mass: "140.9", category: 'lanthanide', group: 3, period: 6, gridX: 6, gridY: 9, electron_configuration: "[Xe] 4f3 6s2", density: 6.77, melt: 1208, boil: 3793, discovered_by: "Carl Auer von Welsbach", year_discovered: 1885, summary: "Praseodymium is a soft metal valued for its magnetic, electrical, chemical, and optical properties. It is used in high-strength magnets and yellow glass coloring." },
  { number: 60, symbol: 'Nd', name: 'Neodymium', atomic_mass: "144.2", category: 'lanthanide', group: 3, period: 6, gridX: 7, gridY: 9, electron_configuration: "[Xe] 4f4 6s2", density: 7.01, melt: 1297, boil: 3347, discovered_by: "Carl Auer von Welsbach", year_discovered: 1885, summary: "Neodymium is best known for creating the world's strongest permanent magnets (NdFeB), essential for electric motors, hard drives, and headphones." },
  { number: 61, symbol: 'Pm', name: 'Promethium', atomic_mass: "[145]", category: 'lanthanide', group: 3, period: 6, gridX: 8, gridY: 9, electron_configuration: "[Xe] 4f5 6s2", density: 7.26, melt: 1315, boil: 3273, discovered_by: "Chien Shiung Wu", year_discovered: 1945, summary: "Promethium is the only radioactive lanthanide and is extremely rare in nature. It produces a pale blue or green glow in the dark and is used in atomic batteries." },
  { number: 62, symbol: 'Sm', name: 'Samarium', atomic_mass: "150.4", category: 'lanthanide', group: 3, period: 6, gridX: 9, gridY: 9, electron_configuration: "[Xe] 4f6 6s2", density: 7.52, melt: 1345, boil: 2067, discovered_by: "Lecoq de Boisbaudran", year_discovered: 1879, summary: "Samarium is a hard silvery metal used in magnets (SmCo), which are less powerful than neodymium ones but can withstand higher temperatures." },
  { number: 63, symbol: 'Eu', name: 'Europium', atomic_mass: "152.0", category: 'lanthanide', group: 3, period: 6, gridX: 10, gridY: 9, electron_configuration: "[Xe] 4f7 6s2", density: 5.244, melt: 1099, boil: 1802, discovered_by: "Eugène-Anatole Demarçay", year_discovered: 1901, summary: "Europium is the most reactive rare-earth element. It is critical for red phosphors in television screens and fluorescent lights." },
  { number: 64, symbol: 'Gd', name: 'Gadolinium', atomic_mass: "157.3", category: 'lanthanide', group: 3, period: 6, gridX: 11, gridY: 9, electron_configuration: "[Xe] 4f7 5d1 6s2", density: 7.90, melt: 1585, boil: 3546, discovered_by: "Jean Charles Galissard de Marignac", year_discovered: 1880, summary: "Gadolinium has exceptional magnetic properties and is widely used as a contrast agent in MRI scans to improve image clarity." },
  { number: 65, symbol: 'Tb', name: 'Terbium', atomic_mass: "158.9", category: 'lanthanide', group: 3, period: 6, gridX: 12, gridY: 9, electron_configuration: "[Xe] 4f9 6s2", density: 8.23, melt: 1629, boil: 3503, discovered_by: "Carl Gustaf Mosander", year_discovered: 1843, summary: "Terbium is a silvery-white rare earth metal. It is used to produce green phosphors for fluorescent lamps and TV tubes, and in magnetostrictive alloys." },
  { number: 66, symbol: 'Dy', name: 'Dysprosium', atomic_mass: "162.5", category: 'lanthanide', group: 3, period: 6, gridX: 13, gridY: 9, electron_configuration: "[Xe] 4f10 6s2", density: 8.540, melt: 1680, boil: 2840, discovered_by: "Lecoq de Boisbaudran", year_discovered: 1886, summary: "Dysprosium has a very high magnetic susceptibility. It is used in control rods for nuclear reactors and to improve the thermal stability of neodymium magnets." },
  { number: 67, symbol: 'Ho', name: 'Holmium', atomic_mass: "164.9", category: 'lanthanide', group: 3, period: 6, gridX: 14, gridY: 9, electron_configuration: "[Xe] 4f11 6s2", density: 8.79, melt: 1734, boil: 2993, discovered_by: "Marc Delafontaine", year_discovered: 1878, summary: "Holmium has the highest magnetic strength of any element. It is used in medical lasers for surgery and to color glass yellow or red." },
  { number: 68, symbol: 'Er', name: 'Erbium', atomic_mass: "167.3", category: 'lanthanide', group: 3, period: 6, gridX: 15, gridY: 9, electron_configuration: "[Xe] 4f12 6s2", density: 9.066, melt: 1802, boil: 3141, discovered_by: "Carl Gustaf Mosander", year_discovered: 1843, summary: "Erbium ions emit light at wavelengths ideal for optical fiber amplification, making it a cornerstone of global fiber-optic communication." },
  { number: 69, symbol: 'Tm', name: 'Thulium', atomic_mass: "168.9", category: 'lanthanide', group: 3, period: 6, gridX: 16, gridY: 9, electron_configuration: "[Xe] 4f13 6s2", density: 9.32, melt: 1818, boil: 2223, discovered_by: "Per Teodor Cleve", year_discovered: 1879, summary: "Thulium is the rarest of the stable lanthanides. It is used in portable X-ray devices and solid-state lasers." },
  { number: 70, symbol: 'Yb', name: 'Ytterbium', atomic_mass: "173.0", category: 'lanthanide', group: 3, period: 6, gridX: 17, gridY: 9, electron_configuration: "[Xe] 4f14 6s2", density: 6.90, melt: 1097, boil: 1469, discovered_by: "Jean Charles Galissard de Marignac", year_discovered: 1878, summary: "Ytterbium is a soft, malleable rare earth used in atomic clocks, fiber optic amplifiers, and stress gauges for earthquakes." },
  { number: 71, symbol: 'Lu', name: 'Lutetium', atomic_mass: "175.0", category: 'lanthanide', group: 3, period: 6, gridX: 18, gridY: 9, electron_configuration: "[Xe] 4f14 5d1 6s2", density: 9.841, melt: 1925, boil: 3675, discovered_by: "Georges Urbain", year_discovered: 1907, summary: "Lutetium is the heaviest and hardest lanthanide. It is very expensive and used in PET scan detectors and refinery catalysts." },
  
  // Period 6 continued
  { number: 72, symbol: 'Hf', name: 'Hafnium', atomic_mass: "178.5", category: 'transition-metal', group: 4, period: 6, gridX: 4, gridY: 6, electron_configuration: "[Xe] 4f14 5d2 6s2", density: 13.31, melt: 2506, boil: 4876, discovered_by: "Dirk Coster", year_discovered: 1923, summary: "Hafnium is chemically almost identical to zirconium. It is a critical material for control rods in nuclear submarines and modern microprocessor insulators." },
  { number: 73, symbol: 'Ta', name: 'Tantalum', atomic_mass: "180.9", category: 'transition-metal', group: 5, period: 6, gridX: 5, gridY: 6, electron_configuration: "[Xe] 4f14 5d3 6s2", density: 16.69, melt: 3290, boil: 5731, discovered_by: "Anders Gustaf Ekeberg", year_discovered: 1802, summary: "Tantalum is a dense, blue-grey metal, highly resistant to corrosion. It is essential for high-performance capacitors in mobile phones and medical implants." },
  { number: 74, symbol: 'W', name: 'Tungsten', atomic_mass: "183.8", category: 'transition-metal', group: 6, period: 6, gridX: 6, gridY: 6, electron_configuration: "[Xe] 4f14 5d4 6s2", density: 19.25, melt: 3695, boil: 5828, discovered_by: "Fausto Elhuyar", year_discovered: 1783, summary: "Tungsten has the highest melting point of all elements. It is used in light bulb filaments, rocket nozzles, and armor-piercing ammunition." },
  { number: 75, symbol: 'Re', name: 'Rhenium', atomic_mass: "186.2", category: 'transition-metal', group: 7, period: 6, gridX: 7, gridY: 6, electron_configuration: "[Xe] 4f14 5d5 6s2", density: 21.02, melt: 3459, boil: 5869, discovered_by: "Masataka Ogawa", year_discovered: 1908, summary: "Rhenium is one of the rarest elements. It has the third-highest melting point and is used in superalloys for jet engines." },
  { number: 76, symbol: 'Os', name: 'Osmium', atomic_mass: "190.2", category: 'transition-metal', group: 8, period: 6, gridX: 8, gridY: 6, electron_configuration: "[Xe] 4f14 5d6 6s2", density: 22.59, melt: 3306, boil: 5285, discovered_by: "Smithson Tennant", year_discovered: 1803, summary: "Osmium is the densest naturally occurring element. It is hard, brittle, and blue-grey, used in fountain pen tips and electrical contacts." },
  { number: 77, symbol: 'Ir', name: 'Iridium', atomic_mass: "192.2", category: 'transition-metal', group: 9, period: 6, gridX: 9, gridY: 6, electron_configuration: "[Xe] 4f14 5d7 6s2", density: 22.56, melt: 2719, boil: 4701, discovered_by: "Smithson Tennant", year_discovered: 1803, summary: "Iridium is the most corrosion-resistant metal known. A layer of iridium in the Earth's crust is evidence of the asteroid impact that killed the dinosaurs." },
  { number: 78, symbol: 'Pt', name: 'Platinum', atomic_mass: "195.1", category: 'transition-metal', group: 10, period: 6, gridX: 10, gridY: 6, electron_configuration: "[Xe] 4f14 5d9 6s1", density: 21.45, melt: 2041.4, boil: 4098, discovered_by: "Antonio de Ulloa", year_discovered: 1735, summary: "Platinum is a dense, malleable, unreactive precious metal. It is vital for catalytic converters, laboratory equipment, and jewelry." },
  { number: 79, symbol: 'Au', name: 'Gold', atomic_mass: "197.0", category: 'transition-metal', group: 11, period: 6, gridX: 11, gridY: 6, electron_configuration: "[Xe] 4f14 5d10 6s1", density: 19.3, melt: 1337.33, boil: 3129, discovered_by: "Ancient", year_discovered: "Ancient", summary: "Gold is the most malleable of all metals; a single gram can be beaten into a sheet of one square meter. It has been the standard of value for millennia." },
  { number: 80, symbol: 'Hg', name: 'Mercury', atomic_mass: "200.6", category: 'transition-metal', group: 12, period: 6, gridX: 12, gridY: 6, electron_configuration: "[Xe] 4f14 5d10 6s2", density: 13.534, melt: 234.32, boil: 629.88, discovered_by: "Ancient", year_discovered: "Ancient", summary: "Mercury is the only metal that is liquid at standard conditions. It is heavy, toxic, and used in thermometers, barometers, and amalgam fillings." },
  { number: 81, symbol: 'Tl', name: 'Thallium', atomic_mass: "204.4", category: 'post-transition-metal', group: 13, period: 6, gridX: 13, gridY: 6, electron_configuration: "[Xe] 4f14 5d10 6s2 6p1", density: 11.85, melt: 577, boil: 1746, discovered_by: "William Crookes", year_discovered: 1861, summary: "Thallium is a toxic post-transition metal that was historically used as rat poison and insecticide. It is soft enough to be cut with a knife." },
  { number: 82, symbol: 'Pb', name: 'Lead', atomic_mass: "207.2", category: 'post-transition-metal', group: 14, period: 6, gridX: 14, gridY: 6, electron_configuration: "[Xe] 4f14 5d10 6s2 6p2", density: 11.34, melt: 600.61, boil: 2022, discovered_by: "Ancient", year_discovered: "Ancient", summary: "Lead is a heavy, soft, malleable metal. It has been used for plumbing and bullets for thousands of years, but is now restricted due to neurotoxicity." },
  { number: 83, symbol: 'Bi', name: 'Bismuth', atomic_mass: "209.0", category: 'post-transition-metal', group: 15, period: 6, gridX: 15, gridY: 6, electron_configuration: "[Xe] 4f14 5d10 6s2 6p3", density: 9.78, melt: 544.7, boil: 1837, discovered_by: "Claude François Geoffroy", year_discovered: 1753, summary: "Bismuth is a brittle metal with a pinkish hue. It creates stunning iridescent hopper crystals and is used in medicines like Pepto-Bismol." },
  { number: 84, symbol: 'Po', name: 'Polonium', atomic_mass: "[209]", category: 'metalloid', group: 16, period: 6, gridX: 16, gridY: 6, electron_configuration: "[Xe] 4f14 5d10 6s2 6p4", density: 9.196, melt: 527, boil: 1235, discovered_by: "Marie Curie", year_discovered: 1898, summary: "Polonium is a highly radioactive and toxic element discovered by Marie Curie and named after Poland. It is used in anti-static brushes and nuclear heat sources." },
  { number: 85, symbol: 'At', name: 'Astatine', atomic_mass: "[210]", category: 'halogen', group: 17, period: 6, gridX: 17, gridY: 6, electron_configuration: "[Xe] 4f14 5d10 6s2 6p5", density: 6.35, melt: 575, boil: 610, discovered_by: "Dale R. Corson", year_discovered: 1940, summary: "Astatine is the rarest naturally occurring element in the Earth's crust. It is highly radioactive and decays quickly, making it difficult to study." },
  { number: 86, symbol: 'Rn', name: 'Radon', atomic_mass: "[222]", category: 'noble-gas', group: 18, period: 6, gridX: 18, gridY: 6, electron_configuration: "[Xe] 4f14 5d10 6s2 6p6", density: 9.73, melt: 202, boil: 211.3, discovered_by: "Friedrich Ernst Dorn", year_discovered: 1900, summary: "Radon is a radioactive gas produced by the decay of uranium in soil. It accumulates in basements and is a leading cause of lung cancer." },

  // Period 7
  { number: 87, symbol: 'Fr', name: 'Francium', atomic_mass: "[223]", category: 'alkali-metal', group: 1, period: 7, gridX: 1, gridY: 7, electron_configuration: "[Rn] 7s1", density: 1.87, melt: 300, boil: 950, discovered_by: "Marguerite Perey", year_discovered: 1939, summary: "Francium is the second rarest naturally occurring element. It is extremely radioactive and has never been viewed in bulk." },
  { number: 88, symbol: 'Ra', name: 'Radium', atomic_mass: "[226]", category: 'alkaline-earth-metal', group: 2, period: 7, gridX: 2, gridY: 7, electron_configuration: "[Rn] 7s2", density: 5.5, melt: 973, boil: 2010, discovered_by: "Marie Curie", year_discovered: 1898, summary: "Radium is a luminescent radioactive metal. It was once used in luminous paints for watches before its severe health hazards were understood." },
  
  // Actinides (grid row 10)
  { number: 89, symbol: 'Ac', name: 'Actinium', atomic_mass: "[227]", category: 'actinide', group: 3, period: 7, gridX: 4, gridY: 10, electron_configuration: "[Rn] 6d1 7s2", density: 10, melt: 1323, boil: 3471, discovered_by: "Friedrich Oskar Giesel", year_discovered: 1902, summary: "Actinium is a glowing blue radioactive metal. It is 150 times more radioactive than radium and is used in experimental cancer treatments." },
  { number: 90, symbol: 'Th', name: 'Thorium', atomic_mass: "232.0", category: 'actinide', group: 3, period: 7, gridX: 5, gridY: 10, electron_configuration: "[Rn] 6d2 7s2", density: 11.7, melt: 2023, boil: 5061, discovered_by: "Jöns Jacob Berzelius", year_discovered: 1829, summary: "Thorium is a weakly radioactive metal that is more abundant than uranium. It is a potential fuel for cleaner, safer nuclear energy." },
  { number: 91, symbol: 'Pa', name: 'Protactinium', atomic_mass: "231.0", category: 'actinide', group: 3, period: 7, gridX: 6, gridY: 10, electron_configuration: "[Rn] 5f2 6d1 7s2", density: 15.37, melt: 1841, boil: 4300, discovered_by: "William Crookes", year_discovered: 1913, summary: "Protactinium is a dense, silvery-grey radioactive metal. It occurs naturally in uranium ores and is highly toxic and radiotoxic." },
  { number: 92, symbol: 'U', name: 'Uranium', atomic_mass: "238.0", category: 'actinide', group: 3, period: 7, gridX: 7, gridY: 10, electron_configuration: "[Rn] 5f3 6d1 7s2", density: 19.1, melt: 1405.3, boil: 4404, discovered_by: "Martin Heinrich Klaproth", year_discovered: 1789, summary: "Uranium is the heaviest naturally occurring element found in significant quantities. Its isotope U-235 is the primary fuel for nuclear reactors and weapons." },
  { number: 93, symbol: 'Np', name: 'Neptunium', atomic_mass: "[237]", category: 'actinide', group: 3, period: 7, gridX: 8, gridY: 10, electron_configuration: "[Rn] 5f4 6d1 7s2", density: 20.45, melt: 917, boil: 4273, discovered_by: "Edwin McMillan", year_discovered: 1940, summary: "Neptunium was the first transuranic element synthesized. It is a byproduct of nuclear reactors and is used in neutron detectors." },
  { number: 94, symbol: 'Pu', name: 'Plutonium', atomic_mass: "[244]", category: 'actinide', group: 3, period: 7, gridX: 9, gridY: 10, electron_configuration: "[Rn] 5f6 7s2", density: 19.816, melt: 912.5, boil: 3501, discovered_by: "Glenn T. Seaborg", year_discovered: 1940, summary: "Plutonium is a fissile radioactive metal used in nuclear weapons and radioisotope thermoelectric generators (RTGs) for spacecraft like Voyager and Curiosity." },
  { number: 95, symbol: 'Am', name: 'Americium', atomic_mass: "[243]", category: 'actinide', group: 3, period: 7, gridX: 10, gridY: 10, electron_configuration: "[Rn] 5f7 7s2", density: 12, melt: 1449, boil: 2880, discovered_by: "Glenn T. Seaborg", year_discovered: 1944, summary: "Americium is a synthetic radioactive element. It is commonly found in household smoke detectors in minute quantities." },
  { number: 96, symbol: 'Cm', name: 'Curium', atomic_mass: "[247]", category: 'actinide', group: 3, period: 7, gridX: 11, gridY: 10, electron_configuration: "[Rn] 5f7 6d1 7s2", density: 13.51, melt: 1613, boil: 3383, discovered_by: "Glenn T. Seaborg", year_discovered: 1944, summary: "Curium is a hard, dense radioactive metal that glows purple in the dark. It is used in X-ray spectrometers for space missions, including Mars rovers." },
  { number: 97, symbol: 'Bk', name: 'Berkelium', atomic_mass: "[247]", category: 'actinide', group: 3, period: 7, gridX: 12, gridY: 10, electron_configuration: "[Rn] 5f9 7s2", density: 14.78, melt: 1259, boil: 2900, discovered_by: "Glenn T. Seaborg", year_discovered: 1949, summary: "Berkelium is a synthetic radioactive element synthesized in California. It has no commercial applications but is used to synthesize heavier elements." },
  { number: 98, symbol: 'Cf', name: 'Californium', atomic_mass: "[251]", category: 'actinide', group: 3, period: 7, gridX: 13, gridY: 10, electron_configuration: "[Rn] 5f10 7s2", density: 15.1, melt: 1173, boil: 1743, discovered_by: "Glenn T. Seaborg", year_discovered: 1950, summary: "Californium is a very strong neutron emitter. It is used to start nuclear reactors and in devices to detect gold, oil, and water layers." },
  { number: 99, symbol: 'Es', name: 'Einsteinium', atomic_mass: "[252]", category: 'actinide', group: 3, period: 7, gridX: 14, gridY: 10, electron_configuration: "[Rn] 5f11 7s2", density: 8.84, melt: 1133, boil: 1269, discovered_by: "Albert Ghiorso", year_discovered: 1952, summary: "Einsteinium was discovered in the debris of the first hydrogen bomb explosion. It is highly radioactive and difficult to study." },
  { number: 100, symbol: 'Fm', name: 'Fermium', atomic_mass: "[257]", category: 'actinide', group: 3, period: 7, gridX: 15, gridY: 10, electron_configuration: "[Rn] 5f12 7s2", density: null, melt: 1800, boil: null, discovered_by: "Albert Ghiorso", year_discovered: 1952, summary: "Fermium is the heaviest element that can be formed by neutron bombardment of lighter elements. It is purely synthetic and has no practical uses." },
  { number: 101, symbol: 'Md', name: 'Mendelevium', atomic_mass: "[258]", category: 'actinide', group: 3, period: 7, gridX: 16, gridY: 10, electron_configuration: "[Rn] 5f13 7s2", density: null, melt: 1100, boil: null, discovered_by: "Albert Ghiorso", year_discovered: 1955, summary: "Mendelevium was the first element to be synthesized one atom at a time. It is named after Dmitri Mendeleev, the father of the periodic table." },
  { number: 102, symbol: 'No', name: 'Nobelium', atomic_mass: "[259]", category: 'actinide', group: 3, period: 7, gridX: 17, gridY: 10, electron_configuration: "[Rn] 5f14 7s2", density: null, melt: 1100, boil: null, discovered_by: "Albert Ghiorso", year_discovered: 1966, summary: "Nobelium is a synthetic element named after Alfred Nobel. Little is known about it outside of its basic nuclear properties." },
  { number: 103, symbol: 'Lr', name: 'Lawrencium', atomic_mass: "[262]", category: 'actinide', group: 3, period: 7, gridX: 18, gridY: 10, electron_configuration: "[Rn] 5f14 7s2 7p1", density: null, melt: 1900, boil: null, discovered_by: "Albert Ghiorso", year_discovered: 1961, summary: "Lawrencium is the final member of the actinide series. Experiments suggest it behaves like a heavier homolog to lutetium." },
  
  // Period 7 continued
  { number: 104, symbol: 'Rf', name: 'Rutherfordium', atomic_mass: "[267]", category: 'transition-metal', group: 4, period: 7, gridX: 4, gridY: 7, electron_configuration: "[Rn] 5f14 6d2 7s2", density: 23.2, melt: 2400, boil: 5800, discovered_by: "Joint Institute for Nuclear Research", year_discovered: 1964, summary: "Rutherfordium was the first superheavy element discovered. It is a highly radioactive synthetic element that decays rapidly." },
  { number: 105, symbol: 'Db', name: 'Dubnium', atomic_mass: "[268]", category: 'transition-metal', group: 5, period: 7, gridX: 5, gridY: 7, electron_configuration: "[Rn] 5f14 6d3 7s2", density: 29.3, melt: null, boil: null, discovered_by: "Joint Institute for Nuclear Research", year_discovered: 1968, summary: "Dubnium is a synthetic element named after Dubna, Russia. Its chemical properties are similar to tantalum but are difficult to verify due to short half-lives." },
  { number: 106, symbol: 'Sg', name: 'Seaborgium', atomic_mass: "[269]", category: 'transition-metal', group: 6, period: 7, gridX: 6, gridY: 7, electron_configuration: "[Rn] 5f14 6d4 7s2", density: 35.0, melt: null, boil: null, discovered_by: "Lawrence Berkeley National Laboratory", year_discovered: 1974, summary: "Seaborgium is named after Glenn T. Seaborg, the only person to have an element named after them while they were still alive." },
  { number: 107, symbol: 'Bh', name: 'Bohrium', atomic_mass: "[270]", category: 'transition-metal', group: 7, period: 7, gridX: 7, gridY: 7, electron_configuration: "[Rn] 5f14 6d5 7s2", density: 37.1, melt: null, boil: null, discovered_by: "GSI Helmholtz Centre", year_discovered: 1981, summary: "Bohrium is a synthetic element named after physicist Niels Bohr. It is expected to resemble rhenium chemically." },
  { number: 108, symbol: 'Hs', name: 'Hassium', atomic_mass: "[270]", category: 'transition-metal', group: 8, period: 7, gridX: 8, gridY: 7, electron_configuration: "[Rn] 5f14 6d6 7s2", density: 40.7, melt: null, boil: null, discovered_by: "GSI Helmholtz Centre", year_discovered: 1984, summary: "Hassium is expected to be the densest of all elements, nearly double the density of osmium. However, only a few atoms have ever been made." },
  { number: 109, symbol: 'Mt', name: 'Meitnerium', atomic_mass: "[278]", category: 'unknown', group: 9, period: 7, gridX: 9, gridY: 7, electron_configuration: "[Rn] 5f14 6d7 7s2", density: 37.4, melt: null, boil: null, discovered_by: "GSI Helmholtz Centre", year_discovered: 1982, summary: "Meitnerium is a synthetic element named after Lise Meitner, a pioneer of nuclear fission. Its properties are largely unknown due to its short existence." },
  { number: 110, symbol: 'Ds', name: 'Darmstadtium', atomic_mass: "[281]", category: 'unknown', group: 10, period: 7, gridX: 10, gridY: 7, electron_configuration: "[Rn] 5f14 6d8 7s2", density: 34.8, melt: null, boil: null, discovered_by: "GSI Helmholtz Centre", year_discovered: 1994, summary: "Darmstadtium was first synthesized in Darmstadt, Germany. It is an extremely heavy and unstable metal that decays in microseconds." },
  { number: 111, symbol: 'Rg', name: 'Roentgenium', atomic_mass: "[282]", category: 'unknown', group: 11, period: 7, gridX: 11, gridY: 7, electron_configuration: "[Rn] 5f14 6d9 7s2", density: 28.7, melt: null, boil: null, discovered_by: "GSI Helmholtz Centre", year_discovered: 1994, summary: "Roentgenium is named after Wilhelm Röntgen, discoverer of X-rays. It belongs to the same group as copper, silver, and gold." },
  { number: 112, symbol: 'Cn', name: 'Copernicium', atomic_mass: "[285]", category: 'transition-metal', group: 12, period: 7, gridX: 12, gridY: 7, electron_configuration: "[Rn] 5f14 6d10 7s2", density: 23.7, melt: null, boil: 357, discovered_by: "GSI Helmholtz Centre", year_discovered: 1996, summary: "Copernicium is fascinating because relativistic effects may make it a liquid metal at room temperature, similar to mercury, but highly radioactive." },
  { number: 113, symbol: 'Nh', name: 'Nihonium', atomic_mass: "[286]", category: 'post-transition-metal', group: 13, period: 7, gridX: 13, gridY: 7, electron_configuration: "[Rn] 5f14 6d10 7s2 7p1", density: 16, melt: 700, boil: 1400, discovered_by: "RIKEN", year_discovered: 2003, summary: "Nihonium is the first element discovered in Asia. It is named after Nihon, the Japanese name for Japan. It is expected to be a post-transition metal." },
  { number: 114, symbol: 'Fl', name: 'Flerovium', atomic_mass: "[289]", category: 'post-transition-metal', group: 14, period: 7, gridX: 14, gridY: 7, electron_configuration: "[Rn] 5f14 6d10 7s2 7p2", density: 14, melt: 340, boil: 420, discovered_by: "Joint Institute for Nuclear Research", year_discovered: 1998, summary: "Flerovium sits in the 'island of stability', where superheavy elements were predicted to be more stable. It might be a volatile metal or even a gas." },
  { number: 115, symbol: 'Mc', name: 'Moscovium', atomic_mass: "[290]", category: 'post-transition-metal', group: 15, period: 7, gridX: 15, gridY: 7, electron_configuration: "[Rn] 5f14 6d10 7s2 7p3", density: 13.5, melt: 670, boil: 1400, discovered_by: "Joint Institute for Nuclear Research", year_discovered: 2003, summary: "Moscovium is a highly radioactive synthetic element. It decays into Nihonium in a fraction of a second and is named after the Moscow region." },
  { number: 116, symbol: 'Lv', name: 'Livermorium', atomic_mass: "[293]", category: 'post-transition-metal', group: 16, period: 7, gridX: 16, gridY: 7, electron_configuration: "[Rn] 5f14 6d10 7s2 7p4", density: 12.9, melt: 709, boil: 1085, discovered_by: "Lawrence Livermore National Laboratory", year_discovered: 2000, summary: "Livermorium is named after the Lawrence Livermore National Laboratory. It is a homolog of polonium and is expected to be a solid post-transition metal." },
  { number: 117, symbol: 'Ts', name: 'Tennessine', atomic_mass: "[294]", category: 'halogen', group: 17, period: 7, gridX: 17, gridY: 7, electron_configuration: "[Rn] 5f14 6d10 7s2 7p5", density: 7.2, melt: 723, boil: 883, discovered_by: "Joint Institute for Nuclear Research", year_discovered: 2009, summary: "Tennessine is a superheavy halogen. Unlike lighter halogens, relativistic effects suggest it might not form diatomic molecules and could be metalloid in nature." },
  { number: 118, symbol: 'Og', name: 'Oganesson', atomic_mass: "[294]", category: 'noble-gas', group: 18, period: 7, gridX: 18, gridY: 7, electron_configuration: "[Rn] 5f14 6d10 7s2 7p6", density: 4.9, melt: 320, boil: 350, discovered_by: "Joint Institute for Nuclear Research", year_discovered: 2002, summary: "Oganesson is the heaviest element known to humanity. Despite being in the noble gas column, relativistic effects predict it is likely a reactive solid semiconductor." },
];

export const getElementByGridPosition = (x: number, y: number): ChemicalElement | undefined => {
  return ELEMENTS.find(e => e.gridX === x && e.gridY === y);
};
